### ISSUE TITLE
SaveFile method of Utilities class

### ISSUE THREAD

**Issue by jasonhendrix** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#104]
The SaveFile method of the Utilities class is commented out.  Without it, the example of saving as a PDF does not work.

**Comment by usmanazizgroupdocs** [comment]
Hi Jason,

Thanks for using GroupDocs.Viewer for .NET.

**SaveFile** method of **Utilities** class accepts the file stream and saves it as a file on the disk. In the example of saving the document as PDF, the method **RenderDocumentAsPDF** uses **SaveFile** method to save file stream as PDF file. Can you please tell us the issue you are facing in this regards? We shall be looking forward to your response.

Warm Regards
