### ISSUE TITLE
[SP-1001] : Implementation of Popup Messages in Case of Exceptions

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#106]
This issue was originally raised via forum thread:
[http://www.groupdocs.com/Community/forums/thread/16392/issue-in-groupdocs-viewer-sharepoint-project.aspx](http://www.groupdocs.com/Community/forums/thread/16392/issue-in-groupdocs-viewer-sharepoint-project.aspx)

User requested to implement the feature of displaying popup messages in case any exception is thrown (as shown in the image). 

![filecorrupted](https://cloud.githubusercontent.com/assets/16013722/17708684/78021d04-63ff-11e6-9b68-4268cf26ab57.png)

**Comment by bobkovalex** [comment]
@usmanazizgroupdocs since we releases new front-end project and this one is deprecated now, can we close this issue?
Thanks.

**Comment by usmanazizgroupdocs** [comment]
@bobkovalex Sure, you can close the issue. 
Regards

**Comment by bobkovalex** [comment]
This feature is available in new front-end examples:
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Dropwizard
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring
