### ISSUE TITLE
Implementation of Sample Document Viewer Application in Windows Forms

### ISSUE THREAD

**Issue by usman-aziz** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#107]
This issue was originally raised via forum thread:
[http://www.groupdocs.com/Community/forums/permalink/16456/16456/showthread.aspx#16456](http://www.groupdocs.com/Community/forums/permalink/16456/16456/showthread.aspx#16456)

The user has asked for a basic document viewer application developed in Windows Forms.

**Comment by bobkovalex** [comment]
@usmanazizgroupdocs since we releases new front-end project and this one is deprecated now, can we close this issue?
Thanks.

**Comment by usmanazizgroupdocs** [comment]
@bobkovalex Since all our front-end projects are web-based (MVC, WebForms), do you have any plans to release desktop apps (i.e. using Windows Forms, etc.)?
Regards

**Comment by usmanazizgroupdocs** [comment]
@bobkovalex Do you have any plans of providing WinForms front end?

**Comment by bobkovalex** [comment]
@usmanazizgroupdocs 

I apologise for not replying sooner. Currently we are not planing on developing any Desktop application, however we will investigate this case and see if we can fit Desktop app development into our scheduler.

Thanks.

**Comment by vladimir-litvinchik** [comment]
@usman-aziz 

Windows Forms example can be found at https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos/WebForms.
