### ISSUE TITLE
Sample Document Viewer in ASP.NET Core using Standard .NET Web API for Document Processing

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#108]
This issue was originally raised via forum thread:
[https://forum.groupdocs.com/t/asp-net-core-mvc/1189/4](https://forum.groupdocs.com/t/asp-net-core-mvc/1189/4)

The user has asked for an example Viewer front end created in ASP.NET Core that makes calls to a standard .NET Framework based ASP.NET Web API where the GroupDocs libraries are hosted to do all of the document processing.

**Comment by ryandtdt** [comment]
Try the best word to asp viewer online directly and easily with high quality on rasteredge page http://www.rasteredge.com/xdoc/html5-viewer/overview/.

**Comment by bobkovalex** [comment]
@usmanazizgroupdocs could you please fix link to the forum.

Thanks.

**Comment by usmanazizgroupdocs** [comment]
@bobkovalex 
GroupDocs.Viewer for .NET now supports .NET Core in v19.10 or later, therefore, this issue can be marked as closed. Thanks
