### ISSUE TITLE
[MVC-10019] : Incorrect Rendering of .msg File 

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#110]
This issue was originally raised via forum thread: [http://www.groupdocs.com/Community/forums/permalink/16865/16865/showthread.aspx#16865](http://www.groupdocs.com/Community/forums/permalink/16865/16865/showthread.aspx#16865)

The user has reported that he is getting issues in viewing the .msg file in MVC front end application. It seems something in the CSS and/or javascript of the legacy viewer is mangling the layout of the document on the client side. Please find the sample .msg file in the forum post mentioned above.

**Comment by aliahmedgroupdocs** [comment]
@usmanazizgroupdocs  added fix for this issue. Thanks.
