### ISSUE TITLE
File packages.config is not found.

### ISSUE THREAD

**Issue by harumburum** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#12]
Please add packages.config file to the GroupDocs.Viewer.Examples.CSharp project.

**Comment by groupdocs-viewer** [comment]
@harumburum Thank you for giving the examples a try + raising an issue and apologies for a delayed response.

Sure - we are looking into it.

**Comment by muhammadumargroupdocs** [comment]
@harumburum The packages.config has been uploaded
