### ISSUE TITLE
[MVC-10026] : Unable to view the documents containing '&' in their file name

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#129]
This issue was originally raised via forum thread:
[http://www.groupdocs.com/Community/forums/thread/17554/file-names-with-ampersand-dont-render.aspx](http://www.groupdocs.com/Community/forums/thread/17554/file-names-with-ampersand-dont-render.aspx)

The user has reported that he is unable to view the files containing '&' sign in their file name. We successfully reproduced the issue at our end. The back end API is rendering the files without any issue however, issue occurs when the file name is passed in the query string i-e ../document-viewer/GetDocumentPageImage?path=de&mo.docx&width=150&quality=100. Thanks

**Comment by aliahmedgroupdocs** [comment]
@usmanazizgroupdocs Commit Added for this issue, Please verify this fix. Thanks.
