### ISSUE TITLE
[MVC-10029] : Email file (.msg) does not render correctly

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#147]
This issue was originally raised via forum threads:
[https://forum.groupdocs.com/t/email-does-not-render-correctly/1810](https://forum.groupdocs.com/t/email-does-not-render-correctly/1810)
[https://forum.groupdocs.com/t/store-cache-on-amazon-s3-generate-cache-on-demand/5429/16?u=usman.aziz](https://forum.groupdocs.com/t/store-cache-on-amazon-s3-generate-cache-on-demand/5429/16?u=usman.aziz)

Using the current ASP.NET MVC Front End showcase, the attached email does not render well in HTML mode in Internet Explorer - it displays with giant text. In Chrome, the images are not loaded. The sample file and screenshots are available in the above-mentioned forum threads. Thanks

**Comment by BrianBoyce** [comment]
Hi, do you have any update on the status of this bug as we are receiving increasing numbers of complaints from our clients. Thanks Brian

**Comment by usmanazizgroupdocs** [comment]
@BrianBoyce,

We apologize for the delayed response. This issue is fixed in our Modern UI front end. You can download Modern UI application from [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App). Please note that we are discontinuing the support of old front ends including ASP.NET_MVC_Front_End and ASP.NET_WebForm_Front_End. Therefore, we recommend you to migrate to the Modern UI front ends (listed below). 

- [GroupDocs.Viewer-for-.NET-MVC-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App)
- [GroupDocs.Viewer-for-.NET-WebForms-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App)

Regards

**Comment by BrianBoyce** [comment]
Usman,

We tried the modern front end but found it to have even more bugs and issues than the current .NET version we are using
Brian

Brian Boyce  |   Director
M: +44 (0)7917 104 579   |   DD: +44 (0)1327 343205   |   T: +44 (0)845 680 1911
E: BBoyce@alphatec.net<mailto:BBoyce@alphatec.net>  |  W: www.alphatec.net<http://www.alphatec.net/>
North Barn, Dodford Hill Farm, Brockhall Road, Dodford, Northamptonshire, NN7 4GS

[Signature]
Alphatec Software Ltd is a company registered in Scotland

Registered office: Eastcroft House, 25 Woodhall Road, Wishaw, North Lanarkshire, ML2 8PY. Registered Number: SC164246

The information contained in this message is confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any use, dissemination, distribution or copying of this message is strictly prohibited. If you have received this message in error, please notify the sender immediately and ensure that all copies of this information are deleted from your computers.

**Comment by usmanazizgroupdocs** [comment]
@BrianBoyce ,

Thanks for your response. Please feel free to share your issues with us [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App/issues). We'll try our best to help you out in this regard. 
Regards
