### ISSUE TITLE
[MVC-10031] : Incorrect rendering of .msg file in HTML based rendering

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#176]
This issue was originally raised via forum thread:
[https://forum.groupdocs.com/t/store-cache-on-amazon-s3-generate-cache-on-demand/5429/14?u=usman.aziz ](https://forum.groupdocs.com/t/store-cache-on-amazon-s3-generate-cache-on-demand/5429/14?u=usman.aziz )

One of the users reported that he is getting the incorrect preview of .msg file. Most of the words get replaced by "page-1" as well. The problematic file is provided in the above-mentioned forum's topic.

**Comment by BrianBoyce** [comment]
Hi Can you please give an update on where you are with this issue as we have customers complaining. Thanks

**Comment by usmanazizgroupdocs** [comment]
@BrianBoyce,

We apologize for the inconvenience. This issue is fixed in our Modern UI front end. You can download Modern UI application from [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App). Please note that we are discontinuing the support of old front ends including ASP.NET_MVC_Front_End and ASP.NET_WebForm_Front_End. Therefore, we recommend you to migrate to the Modern UI front ends (listed below). 

- [GroupDocs.Viewer-for-.NET-MVC-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App)
- [GroupDocs.Viewer-for-.NET-WebForms-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App)

In case you face any difficulties while migrating to Modern UI applications, please feel free to log the issue [here](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App/issues). We'll try our best to help you out in this regard.

Regards
