### ISSUE TITLE
[MVC-1001] : Zooming Options in MVC Front End Application

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#34]
This issue was originally raised via forum thread: [http://groupdocs.com/Community/forums/thread/13101/webformfrontend-errors.aspx](http://groupdocs.com/Community/forums/thread/13101/webformfrontend-errors.aspx)

Implementation of zoom-in and zoom-out options in MVC Front End application which is already implemented in WebForm Front End.

**Comment by groupdocs-viewer** [comment]
This issue is fixed. Please use **showZoom: true** parameter to activate zooming.
