### ISSUE TITLE
[WEBFORM-1004] : Rending image type file in the html based rendering is not working correctly 

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#45]
This issue was originally raised via forum thread: [http://groupdocs.com/Community/forums/thread/13554/image-type-file-render-with-different-zooming-each-time-they-open.aspx](http://groupdocs.com/Community/forums/thread/13554/image-type-file-render-with-different-zooming-each-time-they-open.aspx)

Sometimes images are displaying too small when its render first time, while rendering from cache its displaying large. In both the scenario its not displaying based on its actual size. Even image type files are not rendering in chrome and edge browsers. I have attached few images files you can verify it.
![billgates](https://cloud.githubusercontent.com/assets/16013722/16349424/5107a338-3a72-11e6-9d79-25bf1c670df5.jpg)
![branson](https://cloud.githubusercontent.com/assets/16013722/16349423/51073c72-3a72-11e6-851d-5d05c16aab03.jpg)
![image001](https://cloud.githubusercontent.com/assets/16013722/16349425/51a29e06-3a72-11e6-9f03-268ece1a25fb.png)
![satyaa](https://cloud.githubusercontent.com/assets/16013722/16349426/51ad57ce-3a72-11e6-9bf9-2f0d1183ab68.jpg)

**Comment by muhammadumargroupdocs** [comment]
Solution: Write and set the "useEmScaling" in the JS Configuration Parameters. it can be set either true or false. If it needed to display the image/doc with its orginal size then the property must be set as true or vice versa.
