### ISSUE TITLE
[WEBFORM-1009] : Performance Issue in Rendering Large Documents

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#68]
This issue was originally raised via forum thread:
[http://www.groupdocs.com/Community/forums/thread/14265.aspx](http://www.groupdocs.com/Community/forums/thread/14265.aspx)

Rendering large documents takes considerable time when **showThumbnails** is **true**. After rendering 2 or 3 pages, application starts generating thumbnails and process of rendering pages pauses till all thumbnails are generated. Sample document is attached in the forum thread.

**Comment by PuneetRajak** [comment]
Hi
is there any update on fixes of performance of Viewer when using large document.
What we analyse from observing the Cache folder is that thumbnail only load when the complete caching of the document take place(including the last page of document).
And the complete caching of the document takes a big time due to slow caching performance. 
So in conclusion, the loading of thumbnail is also affected by viewer performance.
we have tried disabling the thumbnail to ensure that it is not due to Thumbnails but the slow rendering of document is still persist. thus it is more relevant to Caching time if big document which does not allow other things to load.
so on emphasising performance, Please look into this with priority and provide any estimate date of release.
thanks.

**Comment by muhammadumargroupdocs** [comment]
Hi Puneet,

Thank you for your work around.

I agree with your observations. In fact performance based isuues are the core level issues of the back-end API. Hence, these issues are already logged in the issue tracking system for the back-end API. Unfortunately, no updates are available for these back-end API issues yet. We'll get back to you once we found any update regarding this particular issue.

Thanks.

**Comment by PuneetRajak** [comment]
Hi,
Please find attached Performance matrix report based on (PreLoad page count(x-axis))/(document page size(y-axis)).
it is comparison between Viewer 2.18 and v3.7 versions.
Viewer with v2.18 is very fast as compare to v3.7.
please let us know your view on this, or any expected date of release for the fix.
Puneet Rajak
[Pre Load Page Count Metrics - Comparisonv2.18.xlsx](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/files/532713/Pre.Load.Page.Count.Metrics.-.Comparisonv2.18.xlsx)

**Comment by muhammadumargroupdocs** [comment]
Hi Puneet,

Thank you for providing us the files. For your information, we already have conducted the performance comparison tests and the results were handed over to the product team. Hence, team is working on it. We'll get back to you as the issues would be resolved.

Thanks.

**Comment by PuneetRajak** [comment]
Hi
I can see there is a new release note
http://www.groupdocs.com/docs/display/viewernet/GroupDocs.Viewer+For+.NET+16.10+Release+Notes
please let me know would that v16.10 has fixes for our issues?

Thanks
Puneet Rajak

**Comment by groupdocs-text** [comment]
Hi Puneet,

Thank you for your note.

Unfortunately, performance based issues couldn't be fixed in the latest monthly released. We'll notify you whenever these particular issues would be resolved.

Thank you

**Comment by muhammadumargroupdocs** [comment]
Hi Puneet,

Thank you for your note.

Unfortunately, performance based issues couldn't be fixed in the latest monthly released. We'll notify you whenever these particular issues would be resolved.

Thank you

**Comment by PuneetRajak** [comment]
Hi
does the new version v16.11 has fixes for our raised issue !

Thanks
Puneet R

**Comment by usmanazizgroupdocs** [comment]
Hi Puneet,

Thanks for writing to us.

We apologize that **GroupDocs.Viewer for .NET 16.11.0** does not contain the fix for performance specific issues. However, we would like you to upgrade your application to the latest version of the API to get a better experience. As we get any further updates related to the performance related issues, we will keep you updated.

Warm Regards

**Comment by usmanazizgroupdocs** [comment]
We have discontinued the support of old front ends including _ASP.NET_MVC_Front_End_ and _ASP.NET_WebForm_Front_End_. Therefore, we recommend you to migrate to our latest front ends (listed below) and share your feedback with us. 

- [GroupDocs.Viewer-for-.NET-MVC-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC-App)
- [GroupDocs.Viewer-for-.NET-WebForms-App](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms-App)

Regards
