### ISSUE TITLE
Split projects into separate repos on github.

### ISSUE THREAD

**Issue by dougludlow** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#93]
Hi, just a suggestion. I was trying to extract the samples and ran in to an error where the path was too long. It may be a good idea to split all of the projects into separate github repos, espcially since most of us are probably only interested in one project and not the whole thing. Another benefit would be that you'd have separate issues for each of the projects. Just an idea. Thanks for putting these out on github!

**Comment by dougludlow** [comment]
So to mitigate the issue of being unable to extract the zip file, I moved the zip from my documents folder to the root of my drive. Now I'm having issues getting the New Front End sample working because of the same issue. I'm getting this error:

```
Server Error in '/' Application.
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. 
```

I had to move the New Front End to my drive root and then it was able to load documents...

**Comment by muhammadumargroupdocs** [comment]
Hi Dougludlow,

Thank you for your suggestion.
FYI, we have published the front-ends versions as repo version releases. 
You can download the front-end autonomously.
Kindly visit the link mentioned below.
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/releases

Have a nice day!

**Comment by dougludlow** [comment]
Thanks!
